name: Run API Tests Every 10 Minutes

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at 12:00 AM  # Runs every 10 minutes
  workflow_dispatch:          # Allows manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Install dependencies without running tests
      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      # 5️⃣ Compile the project
      - name: Compile project
        run: mvn compile

      # 6️⃣ Run API tests
      - name: Run API tests
        run: mvn test
